from . import mail_message
from . import mail_channel
from . import messenger_provider_base
from . import messenger_history
from . import instagram_history
from . import messenger_channel_provider_line
from . import res_partner
from . import res_users
from . import template_components
from . import messenger_template
from . import template_buttons
from . import ir_http
from . import ir_attachment